server:
  port: 8881
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=Australia/Melbourne
    hikari:
      username: root
      password: 123456
      #if version in Maven >= 6.x, then com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        #指定 nacos server的地址
        server-addr: localhost:8848
        #指定 namespace (dev) Nacos功能路径：命名空间 -> 新建命名空间 -> 复制新建命名空间的ID
#        namespace: 47a81bc5-ab3a-4036-afe6-645481d9ee01
        #指定 group
#        group: DEFAULT_GROUP
        #指定 集群cluster
#        cluster-name: Melbourne
  application:
    # use -, do not use _ and special characters
    name: user-center
