server:
  port: 8040
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        #指定 nacos server的地址
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          #让gateway自动从服务发现组件nacos上找到其他微服务
          enabled: true
      routes:
        - id: user_route
          # 访问http://localhost:8040/users/1 即访问 http://user-center/users/1
          uri: lb://user-center
          predicates:
            - Path=/users/**
        - id: content_route
          # 访问http://localhost:8040/shares/1 即访问 http://content-center/shares/1
          uri: lb://content-center
          predicates:
            - Path=/shares/**,/admin/**
# Actuator 暴露所有的端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      #健康检查显示详情
      show-details: always