server:
  port: 8070
spring:
  cloud:
    nacos:
      discovery:
        #指定 nacos discovery server的地址
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          # 让spring cloud gateway 可以从nacos上获取微服务
          enabled: true
  application:
    name: wii

wii:
  # 异构微服务 non-springboot microservice的IP address
  ip: localhost
  # 异构微服务 non-springboot microservice的端口
  port: 8060
  # 异构微服务 non-springboot microservice的健康检查地址（可选）
  health-check-url: http://localhost:8060/health.json